title: KMoberg
description:
author: Karl Mathias Moberg
github: https://github.com/kmoberg
about: Senior Cloud Engineer and Developer, specialized in AWS.
disqus_shortname: stackproblems
google_analytics: UA-XXXXXXXX-Y

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-twitter
      link: "https://twitter.com/mathiasmoberg"
    - icon: fa-linkedin
      link: "https://linkedin.com/u/kmoberg"
    - icon: fa-stack-exchange
      link: "#"
    - icon: fa-github
      link: "https://github.com/kmoberg"

share:
  twitter_username: github.io
  # fb_appid: 1749788565247320

urls:
    - text: About Me
      url: /about/
    #- text: My Projects
    #  url: /projects/
    - text: XML Feed
      url: /feed.xml

url: "https://kmoberg.github.io"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']
